FROM golang:1.25-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git ca-certificates && update-ca-certificates
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOTOOLCHAIN=auto
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main ./cmd/lambda

FROM public.ecr.aws/lambda/go:1
COPY --from=builder /app/main ${LAMBDA_TASK_ROOT}/main
COPY ./data ${LAMBDA_TASK_ROOT}/data
COPY ./templates ${LAMBDA_TASK_ROOT}/templates
CMD ["main"]